name: "Temperature store"
description: "Add-on for store and update temperature schedule!"
version: "1.0.5"
slug: "temperature_store"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  5000/tcp: 5000
map:
  - config:rw